In [8]:
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as pyplot

In [9]:
ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
    
RAW_DIR = ROOT / "data" / "raw"

excel_files = sorted(
    path
    for path in RAW_DIR.glob("*.xlsx")
    if not path.name.startswith("~$")
)

if not excel_files:
    raise FileNotFoundError(f"No .xlsx files found in {RAW_DIR}")

In [10]:
# Change the index if you have multiple files.
DATA_PATH = excel_files[0]

with pd.ExcelFile(DATA_PATH) as workbook:
    print("Workbook:", DATA_PATH.name)
    print("Sheets:", workbook.sheet_names)

    for sheet in workbook.sheet_names:
        print(f"\n--- {sheet} ---")

        # Keep header rows visible until we understand the file layout.
        preview = pd.read_excel(
            workbook,
            sheet_name=sheet,
            header=None,
            nrows=8,
        )

        display(preview)

Workbook: July 2026 Complete Monthly Ridership (with adjustments and estimates)_260901.xlsx
Sheets: ['Read Me', 'Master', 'UPT', 'VRM', 'VRH', 'VOMS', 'UPT Estimates', 'VRM Estimates', 'Calendar Year UPT', 'Calendar Year VRM', 'Mozart Reports']

--- Read Me ---

                                                   0
0                                            Read Me
1                                                NaN
2  Users are encouraged to read the totality of t...
3                                                NaN
4                   1.        General Considerations
5  This Excel workbook contains all Monthly modul...
6  Beginning with Calendar Year 2012, the bottom ...
7  Beginning with Calendar Year 2012, the bottom ...

--- Master ---

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,NTD ID,Legacy NTD ID,Agency,Mode,TOS,3 Mode,Mode/Type of Service Status,Reporter Type,Organization Type,HQ City,...,Last Closed Report Year,Last Closed FY End Month,Last Closed FY End Year,Passenger Miles FY,Unlinked Passenger Trips FY,Avg Trip Length FY,Fares FY,Operating Expenses FY,Avg Cost Per Trip FY,Avg Fares Per Trip FY
1,00001,0001,King County,DR,PT,Bus,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,7519226,1045365,7.192919,895813,96222648,92.046939,0.856938
2,00001,0001,King County,DR,TX,Bus,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,1410322,111550,12.642958,91758,5537616,49.642456,0.822573
3,00001,0001,King County,FB,DO,Ferry,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,1822924,446838,4.079608,1767303,10156716,22.730198,3.955131
4,00001,0001,King County,LR,DO,Rail,Inactive,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2011,12,2011,471587,520933,0.905274,288470,2281393,4.379437,0.553756
5,00001,0001,King County,MB,DO,Bus,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,272281442,72304880,3.765741,63442766,764572298,10.574283,0.877434
6,00001,0001,King County,MB,PT,Bus,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,3280754,814412,4.028371,405215,19334279,23.74017,0.497555
7,00001,0001,King County,SR,DO,Rail,Active,Full Reporter,"City, County or Local Government Unit or Depar...",SEATTLE,...,2024,12,2024,1648929,1492360,1.104914,690874,14848388,9.949602,0.462941

--- UPT ---

,0,1,2,3,4,5,6,7,8,9,...,295,296,297,298,299,300,301,302,303,304
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,10/2025,11/2025,12/2025,1/2026,2/2026,3/2026,4/2026,5/2026,6/2026,7/2026
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,102531,91834,92582,91703,84520,89266,88473,86820,92633,91815
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,16560,13371,12567,15153,16932,22240,24047,20633,18032,18884
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,41613,30987,30358,32219,33418,35172,47918,59522,86707,99081
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,7027582,6034095,5848180,6315539,5912095,6646228,6738016,6932761,6611961,6298063
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,98111,80991,77880,85999,84616,94600,100944,117048,155107,170663
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,141755,116969,118049,103897,101819,133671,141236,139709,143401,145797

--- VRM ---

,0,1,2,3,4,5,6,7,8,9,...,295,296,297,298,299,300,301,302,303,304
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,10/2025,11/2025,12/2025,1/2026,2/2026,3/2026,4/2026,5/2026,6/2026,7/2026
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,715780,623284,630549,531318,494334,516968,506422,507388,541425,548555
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,179700,147459,136741,171832,192006,252198,272689,233975,204480,214141
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,6918,6312,6880,6848,6422,6922,7520,7948,8284,8308
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,2758513,2569323,2727319,2521456,2318820,2581034,2474043,2456134,2443722,2489094
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,132136,115725,131751,124837,116872,127417,127438,141582,163651,159515
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,16187,14343,15732,16205,15881,16660,16396,16202,16399,17011

--- VRH ---

,0,1,2,3,4,5,6,7,8,9,...,295,296,297,298,299,300,301,302,303,304
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,10/2025,11/2025,12/2025,1/2026,2/2026,3/2026,4/2026,5/2026,6/2026,7/2026
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,65790,58958,58968,47211,43884,46055,45409,45564,49002,49941
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,8034,6564,6305,7373,8239,10821,11701,10039,8774,9188
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,610,560,584,586,549,593,656,727,794,762
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,262473,244071,259345,245293,226557,251947,245153,244739,240246,244119
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,11275,9919,10937,10738,10011,11011,11081,12333,13790,14514
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,3341,2961,3249,3233,3168,3244,3163,3127,3210,3265

--- VOMS ---

,0,1,2,3,4,5,6,7,8,9,...,295,296,297,298,299,300,301,302,303,304
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,10/2025,11/2025,12/2025,1/2026,2/2026,3/2026,4/2026,5/2026,6/2026,7/2026
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,370,382,373,423,403,405,407,402,408,407
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,117,114,115,117,117,117,117,117,117,117
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,2,2,2,2,2,2,2,2,2,2
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,742,741,745,752,770,776,778,783,807,806
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,58,58,58,58,58,58,58,58,58,58
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,10,10,10,10,10,10,10,10,10,10

--- UPT Estimates ---

,0,1,2,3,4,5,6,7
0,Top 150,NTD ID,Agency,Mode,TOS,Month,Year,Estimated UPT
1,Y,00012,Municipality of Anchorage,DR,PT,7/2026,2026,16569
2,Y,00018,Ben Franklin Transit,DR,PT,7/2026,2026,25672
3,Y,00018,Ben Franklin Transit,VP,DO,7/2026,2026,26619
4,N,00028,County of Pierce,FB,PT,7/2026,2026,47187
5,N,00034,Rogue Valley Transportation District,DR,PT,7/2026,2026,2617
6,N,00034,Rogue Valley Transportation District,MB,DO,7/2026,2026,55044
7,Y,00040,Central Puget Sound Regional Transit Authority,CB,PT,7/2026,2026,626412

--- VRM Estimates ---

,0,1,2,3,4,5,6,7
0,Top 150,NTD ID,Agency,Mode,TOS,Month,Year,Estimated VRM
1,Y,00012,Municipality of Anchorage,DR,PT,7/2026,2026,90610
2,Y,00018,Ben Franklin Transit,DR,PT,7/2026,2026,122862
3,Y,00018,Ben Franklin Transit,VP,DO,7/2026,2026,191809
4,N,00028,County of Pierce,FB,PT,7/2026,2026,3696
5,N,00034,Rogue Valley Transportation District,DR,PT,7/2026,2026,23089
6,N,00034,Rogue Valley Transportation District,MB,DO,7/2026,2026,49044
7,Y,00040,Central Puget Sound Regional Transit Authority,CB,PT,7/2026,2026,661733

--- Calendar Year UPT ---

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2026.0
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,854155.0,883312.0,887915.0,455391.0,468104.0,552215.0,888663.0,1045365.0,1129315.0,625230.0
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,103861.0,143747.0,177791.0,86460.0,88944.0,110794.0,121496.0,111550.0,148182.0,135921.0
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,599954.0,664365.0,701608.0,146930.0,286843.0,400407.0,399687.0,446838.0,547531.0,394037.0
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,101129569.0,103435175.0,103527532.0,48865810.0,42112037.0,53503564.0,63485248.0,72304880.0,77866225.0,45454663.0
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,883578.0,826450.0,834720.0,391935.0,424166.0,480077.0,623887.0,814412.0,1002310.0,808977.0
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,1417507.0,1685668.0,1863409.0,749443.0,829953.0,1117605.0,1411817.0,1492360.0,1624485.0,909530.0

--- Calendar Year VRM ---

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NTD ID,Legacy NTD ID,Agency,Mode/Type of Service Status,Reporter Type,UACE CD,UZA Name,Mode,TOS,3 Mode,...,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2026.0
1,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,PT,Bus,...,7802103.0,8335875.0,8511613.0,3913186.0,4022799.0,4968632.0,6710756.0,7835166.0,7960962.0,3646410.0
2,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",DR,TX,Bus,...,1411445.0,1675832.0,2052404.0,905250.0,934957.0,1461592.0,1377744.0,1293595.0,1686789.0,1541321.0
3,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",FB,DO,Ferry,...,48762.0,49706.0,52362.0,35948.0,49606.0,51236.0,52310.0,63622.0,76904.0,52252.0
4,00001,0001,King County,Inactive,Full Reporter,80389,"Seattle--Tacoma, WA",LR,DO,Rail,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,DO,Bus,...,32853414.0,33894208.0,35407340.0,30870826.0,30859322.0,29908625.0,29575605.0,30848533.0,31992394.0,17284303.0
6,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",MB,PT,Bus,...,964917.0,970734.0,1058834.0,779440.0,994051.0,907697.0,983035.0,1163529.0,1388679.0,961312.0
7,00001,0001,King County,Active,Full Reporter,80389,"Seattle--Tacoma, WA",SR,DO,Rail,...,193810.0,207850.0,205470.0,147792.0,187454.0,180369.0,177754.0,174111.0,182839.0,114754.0

--- Mozart Reports ---

,0,1
0,1,3781A996C045DEB9D50865B3A4DC1862
1,"<mi app=""e"" ver=""19"">\n <rsloc guid=""3781A996C...",NaN